# config.yaml

# SciML-Bench
# Copyright © 2022 Scientific Machine Learning Research Group
# Scientific Computing Department, Rutherford Appleton Laboratory
# Science and Technology Facilities Council, UK.
# with modifications from Gregor von Laszewski, Juri Papay
# All rights reserved.

# This is a configuration file for the CloudMask benchmark.

name: cloudmask-greene

sbatch:
  mode: h
  dir: localscratch

run:
  filesystem: "/localscratch/{os.USER}"
  # workdir: "/localscratch/{os.USER}/mlcommons/{experiment.TFTTransformerepochs}/{experiment.repeat}"
  venvpath: "/scratch/{os.USER}/ENV3"
  datadir: data
  branch: 'main'
  mode: "parallel"
  # mode: "original"
  # mode: "cloudmesh"

# Submission Information
submission:
  benchmark: cloudmask
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: closed
  version: mlcommons-cloudmask-v1.1
  github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1

experiment:
#  card_name: a100
  card_name: "v100,a100"
  gpu_count: 1
  cpu_num: 1
  mem: "64GB"
  repeat: "11,12,13,14"
  epoch: "1,50,100"
  seed: "1234"
  learningrate: 0.001
  batch_size: 32
  train_split: 0.8
  clip_offset: 15
  no_cache: False
  nodes: 1
  gpu: 1

checkpoint:
  model:
    directory: "output/model-{experiment.epoch}-{experiment.repeat}-{experiment.learningrate}-{os.SLURM_JOB_ID}"
    name: "model.ckpt"


#system:
#  host: "rivanna"
#  python: "3.10.8"
#  num_cpus: 1
#  partition: "bii-gpu"
#  # allocation: ds6011-sp22-002
#  # allocation: bii_dsc
#  allocation: bii_dsc_community
#  reservation: bi_fox_dgx
#  constraint: ""

system:
  host: "greene"
  python: "3.10.8"
  num_cpus: 1
  platform: greene

mask: "float"
data:
  # Training data
  training: "/scratch/{os.USER}/github/data/one-day"
  # Inference data
  inference: "/scratch/{os.USER}/github/data/ssts"

# Model file
model_file: "/scratch/{os.USER}/github/mlcommons/benchmark/cloudmask/target/greene_v5/outputs/cloudModel.h5"

# training 
training_loss: binary_crossentropy
training_metrics: accuracy

# Gregor
gregor: "{os.USER_SCRATCH}/{train_dir}/xyz"
 

# Output directory
output_dir: "/scratch/{os.USER}/github/mlcommons/benchmark/cloudmask/target/greene_v0.5/outputs"

# Log file for recording runtimes
log_file: ./cloudmask_run.log

# Log file for MLCommons logging
mlperf_logfile: ./mlperf_cloudmask.log

image:
  # Size of each patch to feed to the network
  PATCH_SIZE: 256
  # Original height of the image
  IMAGE_H: 1200
  # Original width of the image
  IMAGE_W: 1500
  # No. of channels
  N_CHANNELS: 9
  # Min allowable SST
  MIN_SST: 273.15
  # Amount to crop the edges of the images by
  CROP_SIZE: 80
