# config.yaml

# SciML-Bench
# Copyright © 2022 Scientific Machine Learning Research Group
# Scientific Computing Department, Rutherford Appleton Laboratory
# Science and Technology Facilities Council, UK.
# with modifications from Gregor von Laszewski, Juri Papay
# All rights reserved.

# This is a configuration file for the CloudMask benchmark.

name: cloudmask-greene


sbatch:
  mode: h
  dir: localscratch

run:
  venvpath: "/scratch/{os.USER}/ENV3"
  datadir: "/scratch/{os.USER}/data"
  branch: 'main'
  mode: "parallel"
  # mode: "original"
  # mode: "cloudmesh"

# Submission Information
submission:
  benchmark: cloudmask
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: closed
  version: mlcommons-cloudmask-v1.1
  github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1

experiment:
#  card_name: v100
  card_name: v100
  gpu_count: 1
  cpu_num: 1
  mem: "64GB"
  repeat: "1"
  epoch: 2
  #epoch: 2
  seed: 1234
  learning_rate: 0.001
  batch_size: 32
  train_split: 0.8
  clip_offset: 15
  no_cache: False
  nodes: 1
  gpu: 1
  early_stoppage_patience: "25"
  early_stoppage: "False"

identifier: "{experiment.card_name}-{experiment.early_stoppage}-{experiment.early_stoppage_patience}-{experiment.epoch}-{experiment.learningrate}-{experiment.repeat}"
  
#system:
#  host: "rivanna"
#  python: "3.10.8"
#  num_cpus: 1
#  partition: "bii-gpu"
#  # allocation: ds6011-sp22-002
#  # allocation: bii_dsc
#  allocation: bii_dsc_community
#  reservation: bi_fox_dgx
#  constraint: ""

system:
  host: "greene"
  python: "3.10.8"
  num_cpus: 1
  platform: greene

mask: "float"

# Training data
train_dir: "/scratch/{os.USER}/data/one-day"

# Inference data
inference_dir: "/scratch/{os.USER}/data/ssts"


# training 
training_loss: binary_crossentropy
training_metrics: accuracy


# Output directory
output_dir: "{os.TARGET}/outputs/slstr_cloud"

# Model file
model_file: "{output_dir}/cloudModel-{identifier}.h5"

# Log file for recording runtimes
log_file: "{output_dir}/cloudmask_final_{identifier}.log"

# Log file for MLCommons logging
mlperf_logfile: "{output_dir}/mlperf_cloudmask_final_{identifier}.log"

image:
  # Size of each patch to feed to the network
  PATCH_SIZE: 256
  # Original height of the image
  IMAGE_H: 1200
  # Original width of the image
  IMAGE_W: 1500
  # No. of channels
  N_CHANNELS: 9
  # Min allowable SST
  MIN_SST: 273.15
  # Amount to crop the edges of the images by
  CROP_SIZE: 80

