# stemdlConfig.yaml

# SciML-Bench
# Copyright © 2022 Scientific Machine Learning Research Group
# Scientific Computing Department, Rutherford Appleton Laboratory
# Science and Technology Facilities Council, UK.
# All rights reserved.

# This is a configuration file for STEMDL classification benchmark.

# General info
benchmark: STEMDL
organisation: STFC
division: SciML
status: research
platform: nvidia gtx-2
accelerators_per_node: 6

# Training dir
train_dir: ./data/training

# Test dir
test_dir: ./data/testing

# Validation dir
val_dir: ./data/validation

# Inference dir
inference_dir: ./data/inference

# Log file for recording runtimes
log_file: ./outputs/stemdlLog

# Log file for MLCommons logging
mlperf_logfile: ./outputs/mlperf_stemdl.log

# Model file
model_file : ./outputs/stemdlModel.h5

# Hyperparameters
seed: 1234
learning_rate: 0.001
epochs: 1
batchsize: 32
train_split: 0.8
resnet: resnet50
nodes: 1
gpu: 1
